dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-02/run.sh | bash
notifications:
  slack:
    secure: k0tQyEBLMmRmHaYxB2F6j4IXS4MEY8FCrjgTml246lUoSAhU7p3cX2puO1JlubJeJ3xXDdsLzkoATHurR2Y6BiVVXVrPVbaS/bLoGeqtVllOAYS5PTycZ2RW8HU1PiLQRpRUbMRepoanqZXzEm5+xMy9lLA9lfB2ywEBdpJsO8yqsU5ORhsclOk63z/hI/HxhbvxhQgBH+MPjB7sAHNkikhDA9HGeLQQbdM891bYpQbmJeqzrJqJ0Q/854ENeMVSWlK7t2xT4QXclVdRMUjBuDhGfCpiy6fJvnHs3ACij0Q+fjg/t4khAae65HmKYbk8LiNjX49RH0lle4ZmYhAmlFPDP+unQmeXw+npZip9DA5u0NHg5SsJ1qz1AMcCLLH666jQ781V0PI0SnggGH9gwg/MI8zB3bP5kM8AHyQWoOABf0woA6KNZy0K0ht8OSRiQ4si1aZeSC0iiH7qk3BMY4MSEWLMu6MnMreIpQqQo/hz7L9K2G+Kpl4vn+g5iZS3f9yVr6A2MlZURxD0DvlYb7UEVAQjHTQyryQK47KzM14tFU53Mxya6KMmSUshjbKeqF1p4C+qdOuTDVR8eqxTmirslwrs3O2FMuldtJ93W81Jc16Aj39uuw0hT1jW+0+TUow+QTwOBCu5U+7LHsTUKre/wyhxRJ331JDAH8SaBgg=
