---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "mongodb.fullname" . }}
  labels:
    app: reddit
    component: mongo
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit
      component: mongodb
      release: {{ .Release.Name }}
  template:
    metadata:
      name: {{ template "post.fullname" . }}
      labels:
        app: reddit
        component: mongodb
        release: {{ .Release.Name }}
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        name: mongodb
