version: '3.3'
services:
  db:
    image: mongo:3.2
    volumes:
      - db:/data/db
    networks:
      backend:
  ui:
    image: ovld/ui
    ports:
      - 9292:9292/tcp
    networks:
      frontend:
  post:
    image: ovld/post
    networks:
      backend:
      frontend:
  comment:
    image: ovld/comment
    networks:
      backend:
      frontend:

volumes:
  db:

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.0.1.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
