version: '3.3'
services:
  db:
    image: mongo:3.2
    volumes:
      - db:/data/db
    networks:
      backend:
  ui:
    image: ovld/ui:${TAG}
    ports:
      - 9292:9292/tcp
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    networks:
      frontend:
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
  post:
    image: ovld/post:${TAG}
    networks:
      backend:
      frontend:
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.post
  comment:
    image: ovld/comment:${TAG}
    environment:
      - ZIPKIN_ENABLED=${ZIPKIN_ENABLED}
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: service.ui
    networks:
      backend:
      frontend:

volumes:
  db:

networks:
  frontend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet:  10.0.1.0/24
  backend:
    driver: bridge
    ipam:
      driver: default
      config:
      - subnet: 10.0.2.0/24
