{
 "title": "TelegrafDocker",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Containers CPU THROTTLING PERIODS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_throttling_periods",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers CPU THROTTLING THROTTLED PERIODS",
   "type": "graph",
   "description": "docker_container_cpu_throttling_throttled_periods",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_throttling_throttled_periods",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers CPU USAGE IN KERNEL MODE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_cpu_usage_in_kernelmode[1m])",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "CPU INFO",
   "type": "graph",
   "description": "CPU INFO",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cpu_usage_guest{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_guest_nice{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_idle{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_iowait{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_irq{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_nice{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_softirq{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_steal{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_system{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    },
    {
     "expr": "cpu_usage_user{cpu=\"cpu-total\"}",
     "legendFormat": "{{ __name__}}"
    }
   ]
  },
  {
   "title": "Containers CPU THROTTLING THROTTLED TIME",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_throttling_throttled_time",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers CPU USAGE IN USER MODE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_cpu_usage_in_usermode[1m])",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers CPU USAGE IN PERCENT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_percent",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers CPU USAGE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_cpu_usage_system",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers CPU USAGE TOTAL",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 12 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(docker_container_cpu_usage_total[5m])",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers MEMORY ACTIVE ANON",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_active_anon",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers MEMORY ACTIVE FILE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 7, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_active_file",
     "legendFormat": "{{ container_name }}"
    }
   ]
  },
  {
   "title": "Containers MEMORY CACHE",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 14, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "docker_container_mem_cache", "legendFormat": "{{ container_name }}" }
   ]
  },
  {
   "title": "Containers HIERARCHICAL MEM LIMIT",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "docker_container_mem_hierarchical_memory_limit",
     "legendFormat": "{{ container_name }}"
    }
   ]
  }
 ]
}